[options]
db_host = odoo_db
init = base
db_port = 5432
db_user = odoo20
db_password = odoo20
addons_path = /opt/odoo/odoo/addons,/mnt/custom_addons
log_level = info
admin_passwd = $pbkdf2-sha512$600000$HgNg7L13jnFOCWFM6R1DaA$p.yKALnKxutMFmSGAOf8MfFxZD4F4PzijpBrmru38X7au7sz8D6cqIAQOmXEnCiXpp9OC6xoQnIRn6yzMA/uiQ

