[options]
db_host = odoo_db
db_port = 5432
db_user = odoo20
db_password = odoo20
addons_path = /opt/odoo/odoo/addons,/mnt/custom_addons
log_level = info
default_productivity_apps = True
admin_passwd = $pbkdf2-sha512$600000$HgNg7L13jnFOCWFM6R1DaA$p.yKALnKxutMFmSGAOf8MfFxZD4F4PzijpBrmru38X7au7sz8D6cqIAQOmXEnCiXpp9OC6xoQnIRn6yzMA/uiQ
http_interface = 0.0.0.0
http_port = 8069

[colors]
pid = never
loglevel = auto
session_id = never
http_request_line = auto
http_response_body = auto
perf = auto
cursor_mode = auto
sql = auto
